// GENERATED by scripts/build.mjs from /core. Edit the source in /core, then run npm run build.
(() => {
// Runs inside a claude.ai page (the extension's content script, or Claude
// Desktop's window via the injector). Works out which project the open chat
// belongs to and what the project's idea is: the first prompt of its oldest
// chat, else its description, else its name.
//
// It reads claude.ai's own internal JSON endpoints with the page's session,
// the same calls the web app makes. They are undocumented and can change; a
// failure here only means "no theme", never a broken page.

async function detectClaudeAiProject(loc = location, fetchImpl = fetch) {
  const path = loc.pathname
  const projectMatch = path.match(/^\/project\/([0-9a-f-]{36})/)
  const chatMatch = path.match(/^\/chat\/([0-9a-f-]{36})/)
  if (!projectMatch && !chatMatch) return null

  const getJson = async url => {
    const res = await fetchImpl(url, { credentials: 'include', headers: { accept: 'application/json' } })
    if (!res.ok) throw new Error(`${res.status} ${url}`)
    return res.json()
  }

  const cookieOrg = (typeof document !== 'undefined' ? document.cookie : '').match(/(?:^|;\s*)lastActiveOrg=([0-9a-f-]{36})/)
  let org = cookieOrg && cookieOrg[1]
  if (!org) {
    const orgs = await getJson('/api/organizations')
    org = Array.isArray(orgs) && orgs[0] && orgs[0].uuid
  }
  if (!org) return null
  const base = `/api/organizations/${org}`

  let projectId = projectMatch && projectMatch[1]
  let firstPromptHere = ''
  if (!projectId) {
    const chat = await getJson(`${base}/chat_conversations/${chatMatch[1]}?tree=False&rendering_mode=messages`)
    projectId = chat.project_uuid || (chat.project && chat.project.uuid) || null
    const firstHuman = (chat.chat_messages || []).find(m => m.sender === 'human')
    firstPromptHere = messageText(firstHuman)
    if (!projectId) return { kind: 'chat', key: `chat:${chatMatch[1]}`, name: chat.name || '', idea: firstPromptHere }
  }

  const project = await getJson(`${base}/projects/${projectId}`)
  let idea = ''
  try {
    const chats = await getJson(`${base}/projects/${projectId}/conversations`)
    const oldest = (Array.isArray(chats) ? chats : chats.data || [])
      .slice()
      .sort((a, b) => String(a.created_at).localeCompare(String(b.created_at)))[0]
    if (oldest) {
      const full = await getJson(`${base}/chat_conversations/${oldest.uuid}?tree=False&rendering_mode=messages`)
      idea = messageText((full.chat_messages || []).find(m => m.sender === 'human'))
    }
  } catch {
    idea = firstPromptHere
  }
  return {
    kind: 'project',
    key: `project:${projectId}`,
    name: project.name || '',
    idea: idea || project.description || project.name || '',
  }
}

function messageText(message) {
  if (!message) return ''
  if (typeof message.text === 'string' && message.text) return message.text
  return (message.content || []).filter(b => b.type === 'text').map(b => b.text).join('\n')
}

globalThis.SkinshiftDetect = detectClaudeAiProject
})()
