// Copies the shared core into each target that must ship it inside its own
// folder (a browser extension and a Claude Code plugin can only load their own
// files), and makes a classic-script copy of the claude.ai detector for the
// extension's content script.
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const core = join(root, 'core')
const banner = '// GENERATED by scripts/build.mjs from /core. Edit the source in /core, then run npm run build.\n'

for (const target of ['extension/core', 'claude-code-plugin/hooks/core']) {
  const dest = join(root, target)
  rmSync(dest, { recursive: true, force: true })
  mkdirSync(dest, { recursive: true })
  cpSync(core, dest, { recursive: true })
  writeFileSync(join(dest, 'GENERATED.md'), 'Copied from /core by scripts/build.mjs. Do not edit here.\n')
}
// The plugin needs no network transport or page detector.
rmSync(join(root, 'claude-code-plugin/hooks/core/claudeai-detect.js'))

const detect = readFileSync(join(core, 'claudeai-detect.js'), 'utf8')
  .replace(/^export async function detectClaudeAiProject/m, 'async function detectClaudeAiProject')
writeFileSync(
  join(root, 'extension/detect.js'),
  `${banner}(() => {\n${detect}\nglobalThis.SkinshiftDetect = detectClaudeAiProject\n})()\n`,
)
// Claude Desktop: an expression for webContents.executeJavaScript that resolves the project info.
writeFileSync(
  join(root, 'desktop/detect.generated.cjs'),
  `${banner}module.exports = ${JSON.stringify(`(async () => {\n${detect.replace(/^export /m, '')}\nreturn detectClaudeAiProject(location, fetch)\n})()`)}\n`,
)
console.log('built extension/core, extension/detect.js, claude-code-plugin/hooks/core, desktop/detect.generated.cjs')
