// Packs the Tabler icon set (MIT, https://tabler.io/icons) into one ES module
// the extension loads offline: icon paths plus a search index of names, tags
// and categories. Brand logos are left out (they are trademarks).
//   npm run build:icons
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = join(root, 'node_modules/@tabler/icons')
const read = f => JSON.parse(readFileSync(join(pkg, f), 'utf8'))
const meta = read('icons.json')
const outline = read('tabler-nodes-outline.json')
const filled = read('tabler-nodes-filled.json')
const version = read('package.json').version

const pack = nodes => {
  const out = {}
  for (const [name, list] of Object.entries(nodes)) {
    if (name.startsWith('brand-')) continue
    out[name] = list.map(([, a]) => a.d).filter(d => d && !/^M0 0h24v24H0z$/.test(d)).join('|')
  }
  return out
}
const index = {}
for (const [name, m] of Object.entries(meta)) {
  if (name.startsWith('brand-') || !outline[name]) continue
  index[name] = [m.category || '', ...(m.tags || [])].join(' ').toLowerCase()
}

mkdirSync(join(root, 'core/icons'), { recursive: true })
writeFileSync(join(root, 'core/icons/tabler.js'),
  `// GENERATED by scripts/build-icons.mjs from @tabler/icons ${version} (MIT, see LICENSE-tabler).\n` +
  `export const OUTLINE = ${JSON.stringify(pack(outline))}\n` +
  `export const FILLED = ${JSON.stringify(pack(filled))}\n` +
  `export const INDEX = ${JSON.stringify(index)}\n`)
writeFileSync(join(root, 'core/icons/LICENSE-tabler'), readFileSync(join(pkg, 'LICENSE')))
console.log(`packed ${Object.keys(index).length} Tabler icons`)
